# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from vacationkey import google_key
gmaps.configure(api_key=google_key)

ModuleNotFoundError: No module named 'vacationkey'

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
#import cities.csv from part 1
cities_df = pd.read_csv('../output_data/cities.csv')
cities_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,ostrovnoy,2,RU,1558378754,72,68.05,39.51,37.50,7.16
1,1,mahebourg,75,MU,1558378503,74,-20.41,57.70,78.80,11.41
2,2,qaanaaq,25,GL,1558378755,73,77.48,-69.36,22.20,2.37
3,3,zhuhai,0,CN,1558378755,39,40.71,112.04,44.60,4.47
4,4,cape town,20,ZA,1558378755,76,-33.93,18.42,55.99,8.05

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
locations = cities_df[['Lat','Lng']]
humidity = cities_df['Humidity']

#create a gmap figure
fig = gmaps.figure()

#add the heatmap layer
fig.add_layer(gmaps.heatmap_layer(locations,weights=humidity,dissipating=False, max_intensity=100, point_radius=2))
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
#new df fitting ideal parameters
#A max temperature lower than 75 degrees but higher than 65.
#Wind speed less than 10 mph.
#Zero cloudiness.
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

ideal_df = cities_df.loc[(cities_df['Max Temp'] < 85) & (cities_df['Max Temp']>=75)\
                         & (cities_df['Wind Speed'] < 10)\
                         & (cities_df['Cloudiness'] == 0)] 

#store as a new variable
hotel_df = ideal_df.copy()

hotel_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
88,88,cidreira,0,BR,1558378770,66,-30.17,-50.22,76.56,5.50
125,125,arraial do cabo,0,BR,1558378491,78,-22.97,-42.02,84.20,4.70
138,138,morondava,0,MG,1558378780,69,-20.30,44.28,79.08,9.06
139,139,vaini,0,IN,1558378780,88,15.34,74.49,78.90,1.59
176,176,nador,0,MA,1558378499,40,35.17,-2.93,75.20,6.93
316,316,gunjur,0,GM,1558378848,61,13.18,-16.76,80.60,9.17
518,518,bonito,0,BR,1558378893,49,-21.13,-56.49,84.30,7.72
527,527,tomatlan,0,MX,1558378894,59,19.93,-105.25,84.66,7.90
543,543,yabrud,0,SY,1558378840,32,33.97,36.66,80.60,8.05

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure